apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30800  
  type: NodePort