apiVersion: v1
kind: Service
metadata:
  name: py-service
spec:
  selector:
    app: py-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30900
  type: NodePort